### ISSUE TITLE
Is project accepting contributions?

### ISSUE THREAD

**Issue by technicianted** [solo-io/protoc-gen-openapi#14]
I have a couple of PRs pending and one is on the way but I'm not seeing activity. 

Is this project active and is accepting contributions?

**Comment by shashankram** [comment]
@technicianted yes! Sorry we haven't been very active, but would appreciate any contributions as we look to enhance this tool.

**Comment by AndrewGleason** [comment]
@shashankram follow up on this, is this mean to be a better maintained version of [google's unmaintained version?](https://github.com/google/gnostic/blob/main/openapiv3/)

**Comment by shashankram** [comment]
> @shashankram follow up on this, is this mean to be a better maintained version of [google's unmaintained version?](https://github.com/google/gnostic/blob/main/openapiv3/)

It is primarily used by Solo.io's projects and is customized for that. I don't want to promise anything, but we do actively use this tool and try to keep it stable. We don't anticipate adding new features.

**Comment by shashankram** [comment]
Closing as the original question has been answered.
