### ISSUE TITLE
please help me :) 

### ISSUE THREAD

**Issue by sirtakidancers** [solo-io/protoc-gen-openapi#5]
i have a problem to run i use docker FROM golang:1.19-alpine and after copy i get this error
![Снимок экрана 2022-09-07 в 16 56 42](https://user-images.githubusercontent.com/38262044/188896624-453eeef4-8fff-437b-9305-316e0f411332.png)

**Comment by bartolomej** [comment]
@sirtakidancers  This means that the `protoc-gen-openapi` binary isn't present in your "path".

Try to run just the `protoc-gen-openapi` command. If you get this error:

```bash
command not found: protoc-gen-openapis
```

... this again confirms that the OS can't find the path to the executable file which should be executed when you run `protoc-gen-openapis` command.

You can check what's in your path with `echo $PATH` command.

More info: https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path

**Comment by shashankram** [comment]
You need to add `protoc-gen-openapi` to your PATH variable.
